packages:
  - packages/*
  - packages/@agenticflow/*

catalog:
  # Core dependencies
  react: ^19.1.0
  react-dom: ^19.1.0
  typescript: ^5.7.2
  
  # Build tools
  vite: ^6.2.0
  turbo: ^2.3.3
  tsup: ^8.4.0
  
  # UI libraries
  reactflow: ^11.11.4
  zustand: ^5.0.5
  immer: ^10.0.0
  '@google/genai': ^1.3.0
  react-mentions: ^4.4.10
  
  # Styling
  tailwindcss: ^3.4.0
  '@tailwindcss/forms': ^0.5.7
  postcss: ^8.4.0
  autoprefixer: ^10.4.0
  
  # Testing
  jest: ^29.6.2
  vitest: ^1.0.0
  '@testing-library/react': ^14.0.0
  '@testing-library/jest-dom': ^6.0.0
  
  # Code quality
  '@biomejs/biome': ^1.9.0
  prettier: ^3.0.0
  lefthook: ^1.7.15
  
  # Type definitions
  '@types/node': ^22.14.0
  '@types/react': ^19.1.6
  '@types/react-dom': ^19.1.5
  '@types/jest': ^29.5.3 